### PR TITLE
Start webview-sys lib for extern C functions

### PR DESCRIPTION
**Pull request by carbotaniuman**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [X] New Binding Issue https://github.com/tauri-apps/tauri/issues/543
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes. Issue #___
- [X] No

**The PR fulfills these requirements:**

- [X] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
Still not too sure how the team wants the overall project structure, and I also need a working build.rs to continue the rest of the bindings.

### CODE REVIEW

**Comment by khionu** [comment]
This is what the new repo should be. While there is a pattern in Rust of having an `x` crate and `x-sys` crate when `x` is a C Library, we only need to provide a minimal wrapper over the C API that encapsulates the unsafe. This is the purview of `x-sys` crates. Our `x` crate will need to use our trait, which makes it too specialized for general purpose, which is why I made `tauri-view` inside the monorepo.

**Comment by tensor-programming** [comment]
There are a few things I believe we should also include. a `SizeHint enum` for defining the size of the window (in the c code there are 4 sizes). 

Something alone these lines or you could use `bitflags`. 
```
#[repr(C)]
pub enum SizeHint {
    None = 0,
    Min = 1,
    Max = 2,
    Fixed = 3,
}
```
You also can define the `Webview` and `Window` structs as just empty `Enum` types; makes it easier imo since you don't have any inner type.  And for where we are passing in the callbacks in say `webview_bind` and `webview_dispatch`, we should wrap these in `Option` types. For example:

```
pub fn webview_dispatch(w: *mut Webview, f: Option<DispatchFn>, arg: *mut c_void);
```


Now with regards to the build script, we can re-purpose some of the scripts that zserge uses; `build.bat` and `build.sh`.  Both of those are good guidelines for knowing what we need to pass into the `cc` lib.

For windows I had a fairly basic `build.rs` file that looked something like this:
```

fn main() {
    println!("cargo:rerun-if-changed=webview.h");

    let mut build = Build::new();

    let _target = env::var("TARGET").expect("TARGET environment var not set.");
    build
        .include("webview.h")
        .include("webview2.h")
        .flag_if_supported("-std:c++17")
        .flag_if_supported("-w");

    build.file("webview.cc").file("main.cc");

    println!("cargo:rustc-link-lib={}", "dll/x64/webview.dll");
    println!("cargo:rustc-link-lib={}", "dll/x64/WebView2Loader.dll");

    build.compile("webview.exe");
}
``` 

Personally, I feel that this code probably doesn't fully cut it.  We have more that needs to be included but its a start. For windows, we want to follow the `Building webview.dll` instructions to build our lib with the `build.rs` and for the other platforms we can follow these flags: `-DWEBVIEW_GTK -std=c++11 -Wall -Wextra -pedantic $(pkg-config --cflags --libs gtk+-3.0 webkit2gtk-4.0)` for linux and `-DWEBVIEW_COCOA -std=c++11 -Wall -Wextra -pedantic -framework WebKit` for MacOS.  Notice `pkg-config` is being used in linux; we could have a feature flag in the system library to allow devs to use pkg-config if they have it to install webkit-gtk.

**Comment by khionu** [comment]
I would use `repr(i32)`, since the hint variants are defined as `int`.

**Comment by tensor-programming** [comment]
If you look at the PR i made, I defined them as u8's though maybe i8s would be more accurate.  Thats part of the Bitflags libraries generation.  You can see the interface here: https://github.com/tauri-apps/webview_rust/blob/ca835f0800a27aed0c4e00c00cbe00e427259533/src/lib.rs#L11-L40

Some of these `c_int` fields could probably be replaced with bools too.  Like debug in the first function.

**Comment by khionu** [comment]
The point of making them `i32`s is because the header uses `int`. It's an optimization for CPU over Memory that probably gains us next to nothing, but type consistency makes more sense to me than trying to save for such a short window of time.

**Review by tensor-programming — APPROVED** [review]

**Pull request merged**
