### PR TITLE
chore: bump webview submodule

### PR DESCRIPTION
**Pull request by eliassjogreen**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] New Binding Issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [x] Bump webview

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes. Issue #___
- [x] No

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch and _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by eliassjogreen** [comment]
@justjosias

**Review by justjosias — APPROVED** [review]
LGTM. Everything appears to work as before and there aren't any API changes to cover. 

(I don't have write access to this repository at the moment, so my review doesn't mean much to GitHub)

**Comment by eliassjogreen** [comment]
ah, ok. @lucasfernog maybe?

**Comment by justjosias** [comment]
@eliassjogreen As I now have write access, this can be merged. :+1:

**Pull request merged**
